Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -30,4 +30,20 @@ jobs:
     
     - name : change repo
       run : cd /home/newus-api-services/htdocs/api-services.newus.id/actions-runner/_work/website-be/website-be
-    - run : pm2 restart api-services.newus.id
+    - name : Restart Pm2
+      run  : |
+          APP_NAME="api-services.newus.id"
+          APP_ID="6"
+
+          # Coba restart berdasarkan nama aplikasi
+          if pm2 restart $APP_NAME; then
+            echo "Successfully restarted app with name $APP_NAME"
+          else
+            echo "Failed to restart app with name $APP_NAME, trying with ID $APP_ID"
+            if pm2 restart $APP_ID; then
+              echo "Successfully restarted app with ID $APP_ID"
+            else
+              echo "Failed to restart app with both name and ID"
+              exit 1
+            fi
+          fi
